[build]
  command = "bash netlify-build.sh"
  publish = "frontend/dist"
  base = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_CONFIG_PRODUCTION = "false"
  YARN_ENABLE_IMMUTABLE_INSTALLS = "false"
  YARN_ENABLE_GLOBAL_CACHE = "false"
  DISABLE_YARN_WORKSPACES = "true"


