[build]
  command = "cd frontend && rm -rf ../backend && npm install && npm run build"
  publish = "frontend/dist"
  base = "frontend"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_CONFIG_PRODUCTION = "false"
  YARN_ENABLE_IMMUTABLE_INSTALLS = "false"
  YARN_ENABLE_GLOBAL_CACHE = "false"
  DISABLE_YARN_WORKSPACES = "true"


